spring.application.name=springboot-static-config

# This is usually set to true by default. Include it if you have changed this setting before.
spring.web.resources.add-mappings=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.content-type=text/html
spring.thymeleaf.cache=false
